name: CICD
on:
  clone:
    branches:
      - master
#jobs:
 # test:
#        runs-on: echo "HELLO"
#  steps:
 #   name: Checkout the code
 #   uses: actions/checkout@v3
#  steps:
#   name: Clone Repo
 #   run: git clone git@github.com:Nekit36ru/oddotest.git   
