name: Nekit

on: 
  push
env:
  DEST_FOLDER: "/home/ubuntu/project"
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repositoty
        uses: actions/checkout@v3
      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          source: "${GITHUB_WORKSPACE}/*"
          target: "${DEST_FOLDER}"    


        
