name: Nekit

on: 
  push
  
jobs:
  build:
    runs-on: self-hosted
    steps: 
      - name: Checkout repositoty
        uses: actions/checkout@v3
      #- name: setup Python
       # uses: actions/setup-python@v4
        #with:
         # python-version: "3.10"
      
      #  with:
      #    repository: Nekit36ru/oddotest.git
     #     token: ${{ DEPLOY_KEY }}
      - name: Install requirements
        run: echo "Hello World!!!" && pwd&&ls
