name: Nekit

on: 
  push
env:
  DEST_FOLDER: "/home/ubuntu/project"
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repositoty
        uses: actions/checkout@v3
      - name: prepare tar
        run: |
          mkdir ../TMP_DIR
          cp -r . ../TMP_DIR
          tar cf tmp.tar ../TMP_DIR/*
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: mkdir ${DEST_FOLDER}   
      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          source: tmp.tar
          target: "${DEST_FOLDER}" 
      - name: Untar tmp.tar   
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: tar xf ${DEST_FOLDER}/tmp.dir    


        
