name: CICD
on:
  push:
    branches:
      - master
jobs:
  test:
    name: deploy only changed-files
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v3
    steps:
    - name: Clone Repo
      run: git clone git@github.com:Nekit36ru/oddotest.git   
