name: Nekit

on: 
  push  
jobs:
  build:
    runs-on: self-hosted
    steps: 
      - name: Checkout repositoty
        uses: actions/checkout@v3
      - name: Copy workdir to target dir
        run: |
          cp -r ${GITHUB_WORKSPACE} /home/ubuntu/project


        
