name: CICD
on:
  push:
    branches:
      - master
jobs:
  test:
    name: deploy only changed-files
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v3
    - name: Install 
       run: ls -l
       run: ip a
