name: Python package

on: fork

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install requirements
      run: |
        echo "Hello"

   # - name: Test with pytest
   #   run: |
   #     pytest ./tests
